name: End to End Kuberhealthy Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
      - uses: actions/checkout@v6
      - name: Build container
        id: build
        run: |
          IMAGE="kuberhealthy-e2e:${GITHUB_RUN_ID}"
          echo "IMAGE=$IMAGE"
          docker build --file cmd/kuberhealthy/Containerfile --tag "$IMAGE" .
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
      - name: Export image
        run: docker save ${{ steps.build.outputs.image }} -o kuberhealthy.tar
      - uses: actions/upload-artifact@v7
        with:
          name: kh-image
          path: kuberhealthy.tar

  e2e:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
      - uses: actions/checkout@v6
      - uses: engineerd/setup-kind@v0.6.0
        with:
          version: "v0.32.0"
      - uses: actions/download-artifact@v8
        with:
          name: kh-image
      - name: Load image into kind
        run: kind load image-archive kuberhealthy.tar
      - name: Run end to end test
        env:
          IMAGE_URL: ${{ needs.build-image.outputs.image }}
        run: ./tests/.ci/e2e.sh "${IMAGE_URL}"
